/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_easivend_evprotocol_EVprotocol */

#ifndef _Included_com_easivend_evprotocol_EVprotocol
#define _Included_com_easivend_evprotocol_EVprotocol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_easivend_evprotocol_EVprotocol
 * Method:    EV_portRegister
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_easivend_evprotocol_EVprotocol_EVportRegister
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
